export const QUERY_KEYS = {
  featured:         ['content', 'featured'],
  trending:         ['content', 'trending'],
  newReleases:      ['content', 'new-releases'],
  continueWatching: ['content', 'continue-watching'],
  recommendations:  ['content', 'recommendations'],
  plans:                ['plans'],
  watchlist:            ['watchlist'],
  notifications:        ['notifications'],
  liveStreams:           ['live-streams'],
  progress:    (id) => ['progress', id],
  myCourses:            ['my-courses'],
  analytics:   (t)  => ['analytics', t],
  settings:             ['settings'],
}
